name: podcast_player
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  miniplayer: ^0.4.1+2
  http: ^0.12.2
  animations: ^1.1.2
  shared_preferences: ^0.5.10
  audio_service:
    git:
      url: git://github.com/ryanheise/audio_service.git
  just_audio: ^0.2.2
  positioned_tap_detector: ^1.0.3
  flutter_html: ^1.0.2
  marquee: ^1.6.0
  flutter_custom_tabs: ^0.6.0
  flutter_downloader: ^1.5.0
  image: ^2.1.14
  flutter_cache_manager: ^1.4.1
  google_fonts: ^1.1.0
  xml: ^4.5.0
  file_picker: ^1.13.3
  progress_dialog: ^1.2.4
  permission_handler: ^5.0.1+1
  webview_flutter: ^0.3.22+1
  url_launcher: ^5.5.2
  #TODO: https://pub.dev/packages/quick_actions

#dev_dependencies:
#  flutter_test:
#    sdk: flutter

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/google_fonts/

  fonts:
    - family: PodcastIcons
      fonts:
        - asset: assets/PodcastIcons.ttf