/// Flutter icons PodcastIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PodcastIcons
///      fonts:
///       - asset: fonts/PodcastIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PodcastIcons {
  PodcastIcons._();

  static const _kFontFam = 'PodcastIcons';
  static const _kFontPkg = null;

  static const IconData play_button__1_ = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play_button = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
